language: php
os:
  - linux
dist: xenial

stages:
  - name: syntax
  - name: test
  - name: quality
  - name: deploy

jobs:
  include:
    - stage: syntax
      name: Syntax PHP 5.6
      php: 5.6
      before_script:
        - php --version
      script:
        - find ./src ./test -name "*.php" -print 0 | xargs -0 -n1 php -l
    
    - script:
        - find ./src ./test -name "*.php" -print 0 | xargs -0 -n1 php -l
      name: Syntax PHP 7.2
      php: 7.2
      before_script:
        - php --version
    
    - script:
        - find ./src ./test -name "*.php" -print 0 | xargs -0 -n1 php -l
      name: Syntax PHP 7.4
      php: 7.4
      before_script:
        - php --version
    
    - stage: test
      name: Test PHP 5.6
      php: 5.6
      before_script:
        - phpunit --version
      script:
        - phpunit
    
    - script:
        - phpunit
      name: Test PHP 7.2
      php: 7.2
      before_script:
        - phpunit --version
    
    - script:
        - phpunit
      name: Test PHP 7.4
      php: 7.4
      before_script:
        - phpunit --version
    
    - stage: quality
      name: Quality PHP 5.6
      php: 5.6
      before_script:
        - phpcs --version
      script:
        - phpcs
    
    - script:
        - phpcs
      name: Quality PHP 7.2
      php: 7.2
      before_script:
        - phpcs --version
    
    - script:
        - phpcs
      name: Quality PHP 7.4
      php: 7.4
      before_script:
        - phpcs --version