# v0.2.0

language: php
os:
  - linux
dist: xenial

stages:
  - name: syntax
  - name: test
  - name: quality
  - name: deploy

jobs:
  include:
    # Syntax stage
    - &job_syntax
      stage: syntax
      name: Syntax PHP 5.6
      php: 5.6
      before_script:
        - php --version
      script:
        - find ./src ./test -name "*.php" -print 0 | xargs -0 -n1 php -l
    - <<: *job_syntax
      name: Syntax PHP 7.0
      php: 7.0
    - <<: *job_syntax
      name: Syntax PHP 7.1
      php: 7.1
    - <<: *job_syntax
      name: Syntax PHP 7.2
      php: 7.2
    - <<: *job_syntax
      name: Syntax PHP 7.3
      php: 7.3
    - <<: *job_syntax
      name: Syntax PHP 7.4
      php: 7.4

    # Test stage
    - &job_test
      stage: test
      name: Test PHP 5.6
      php: 5.6
      script:
        - phpunit --version
        - phpunit
    - <<: *job_test
      name: Test PHP 7.0
      php: 7.0
      before_script:
        - curl -OL https://phar.phpunit.de/phpunit-6.phar && chmod +x phpunit-6.phar && sudo mv phpunit-6.phar /home/travis/.phpenv/shims/phpunit
    - <<: *job_test
      name: Test PHP 7.1
      php: 7.1
      before_script:
        - curl -OL https://phar.phpunit.de/phpunit-7.phar && chmod +x phpunit-7.phar && sudo mv phpunit-7.phar /home/travis/.phpenv/shims/phpunit
    - <<: *job_test
      name: Test PHP 7.2
      php: 7.2
    - <<: *job_test
      name: Test PHP 7.3
      php: 7.3
    - <<: *job_test
      name: Test PHP 7.4
      php: 7.4

    # Quality stage
    - &job_quality
      stage: quality
      name: Quality PHP 5.6
      php: 5.6
      before_script:
        - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && chmod +x phpcs.phar && sudo mv phpcs.phar /usr/local/bin/phpcs
        - phpcs --version
      script:
        - phpcs
    - <<: *job_quality
      name: Quality PHP 7.0
      php: 7.0
    - <<: *job_quality
      name: Quality PHP 7.1
      php: 7.1
    - <<: *job_quality
      name: Quality PHP 7.2
      php: 7.2
    - <<: *job_quality
      name: Quality PHP 7.3
      php: 7.3
    - <<: *job_quality
      name: Quality PHP 7.4
      php: 7.4