language: php
os:
  - linux
dist: xenial
php:
  - 5.6
  - 7.2
  - 7.4
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && chmod +x phpcs.phar && sudo mv phpcs.phar /usr/local/bin/phpcs
  - php --version
  - phpunit --version
  - phpcs --version
script:
  