language: php
os:
  - linux
dist: xenial

stages:
  - name: syntax
  - name: test
  - name: quality
  - name: deploy

jobs:
  include:
    - &job_syntax
      stage: syntax
      name: Syntax PHP 5.6
      php: 5.6
      before_script:
        - php --version
      script:
        - find ./src ./test -name "*.php" -print 0 | xargs -0 -n1 php -l
    - <<: *job_syntax
      name: Syntax PHP 7.2
      php: 7.2
    - <<: *job_syntax
      name: Syntax PHP 7.4
      php: 7.4

    - &job_test
      stage: test
      name: Test PHP 5.6
      php: 5.6
      before_script:
        - phpunit --version
      script:
        - phpunit
    - <<: *job_test
      name: Test PHP 7.2
      php: 7.2
    - <<: *job_test
      name: Test PHP 7.4
      php: 7.4

    - &job_quality
      stage: quality
      name: Quality PHP 5.6
      php: 5.6
      before_script:
        - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && chmod +x phpcs.phar && sudo mv phpcs.phar /usr/local/bin/phpcs
        - phpcs --version
      script:
        - phpcs
    - <<: *job_quality
      name: Quality PHP 7.2
      php: 7.2
    - <<: *job_quality
      name: Quality PHP 7.4
      php: 7.4